# Generated by Django 2.0 on 2019-11-28 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191128_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name='被关注者'),
        ),
    ]
